require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CampusesController do

  # This should return the minimal set of attributes required to create a valid
  # Campus. As you add validations to Campus, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CampusesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all campuses as @campuses" do
      campus = Campus.create! valid_attributes
      get :index, {}, valid_session
      assigns(:campuses).should eq([campus])
    end
  end

  describe "GET show" do
    it "assigns the requested campus as @campus" do
      campus = Campus.create! valid_attributes
      get :show, {:id => campus.to_param}, valid_session
      assigns(:campus).should eq(campus)
    end
  end

  describe "GET new" do
    it "assigns a new campus as @campus" do
      get :new, {}, valid_session
      assigns(:campus).should be_a_new(Campus)
    end
  end

  describe "GET edit" do
    it "assigns the requested campus as @campus" do
      campus = Campus.create! valid_attributes
      get :edit, {:id => campus.to_param}, valid_session
      assigns(:campus).should eq(campus)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Campus" do
        expect {
          post :create, {:campus => valid_attributes}, valid_session
        }.to change(Campus, :count).by(1)
      end

      it "assigns a newly created campus as @campus" do
        post :create, {:campus => valid_attributes}, valid_session
        assigns(:campus).should be_a(Campus)
        assigns(:campus).should be_persisted
      end

      it "redirects to the created campus" do
        post :create, {:campus => valid_attributes}, valid_session
        response.should redirect_to(Campus.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved campus as @campus" do
        # Trigger the behavior that occurs when invalid params are submitted
        Campus.any_instance.stub(:save).and_return(false)
        post :create, {:campus => { "name" => "invalid value" }}, valid_session
        assigns(:campus).should be_a_new(Campus)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Campus.any_instance.stub(:save).and_return(false)
        post :create, {:campus => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested campus" do
        campus = Campus.create! valid_attributes
        # Assuming there are no other campuses in the database, this
        # specifies that the Campus created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Campus.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => campus.to_param, :campus => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested campus as @campus" do
        campus = Campus.create! valid_attributes
        put :update, {:id => campus.to_param, :campus => valid_attributes}, valid_session
        assigns(:campus).should eq(campus)
      end

      it "redirects to the campus" do
        campus = Campus.create! valid_attributes
        put :update, {:id => campus.to_param, :campus => valid_attributes}, valid_session
        response.should redirect_to(campus)
      end
    end

    describe "with invalid params" do
      it "assigns the campus as @campus" do
        campus = Campus.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Campus.any_instance.stub(:save).and_return(false)
        put :update, {:id => campus.to_param, :campus => { "name" => "invalid value" }}, valid_session
        assigns(:campus).should eq(campus)
      end

      it "re-renders the 'edit' template" do
        campus = Campus.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Campus.any_instance.stub(:save).and_return(false)
        put :update, {:id => campus.to_param, :campus => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested campus" do
      campus = Campus.create! valid_attributes
      expect {
        delete :destroy, {:id => campus.to_param}, valid_session
      }.to change(Campus, :count).by(-1)
    end

    it "redirects to the campuses list" do
      campus = Campus.create! valid_attributes
      delete :destroy, {:id => campus.to_param}, valid_session
      response.should redirect_to(campuses_url)
    end
  end

end
